version: '3.8'
services:
  paperlessrest:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
    depends_on:
      - postgres
    networks:
      - dms-network

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3-kompatible API
      - "9001:9001"   # MinIO Web-GUI
    volumes:
      - minio_data:/data
    networks:
      - dms-network

  webui:
    build:
      context: ./webui
    ports:
      - "80:80"
    depends_on:
      - paperlessrest
    networks:
      - dms-network

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: paperless_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dms-network

  ocrworker:
    build:
      context: ./OCR-Worker
      dockerfile: Dockerfile
    container_name: paperless_ocr
    depends_on:
      - rabbitmq
      - paperlessrest
    networks:
      - dms-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"  # For RabbitMQ management UI
      - "5672:5672"    # For client connections to RabbitMQ
    networks:
      - dms-network

volumes:
  postgres_data:

  minio_data:
    driver: local

networks:
  dms-network:
    driver: bridge
