server:
  port: ${SERVER_PORT:8081}

springdoc:
  api-docs:
    path: /docs/api
  swagger-ui:
    path: /docs/swaggerui

minio:
  url: http://minio:9000
  accessKey: admin
  secretKey: admin1234
  bucketName: paperless-bucket

spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/paperless_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    sql:
      init:
        mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

